# Generated by Django 5.2.17 on 2026-08-12 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขล่าสุดเมื่อ')),
                ('kind', models.CharField(choices=[('appointment_reminder', 'แจ้งเตือนนัดหมาย'), ('manual', 'ส่งด้วยเจ้าหน้าที่')], default='appointment_reminder', max_length=30, verbose_name='ประเภทข้อความ')),
                ('message', models.TextField(verbose_name='ข้อความที่ส่ง')),
                ('status', models.CharField(choices=[('pending', 'รอส่ง'), ('sent', 'ส่งแล้ว'), ('failed', 'ส่งไม่สำเร็จ')], db_index=True, default='pending', max_length=10, verbose_name='สถานะ')),
                ('provider', models.CharField(blank=True, max_length=20, verbose_name='ผู้ให้บริการที่ใช้ส่ง')),
                ('provider_message_id', models.CharField(blank=True, max_length=100, verbose_name='รหัสอ้างอิงจากผู้ให้บริการ')),
                ('error_message', models.CharField(blank=True, max_length=255, verbose_name='สาเหตุที่ส่งไม่สำเร็จ')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='เวลาที่ส่งสำเร็จ')),
            ],
            options={
                'verbose_name': 'บันทึกการส่ง SMS',
                'verbose_name_plural': 'บันทึกการส่ง SMS',
                'ordering': ['-created_at'],
            },
        ),
    ]
