# Generated by Django 5.2.17 on 2026-08-12 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
        ('notifications', '0001_initial'),
        ('patients', '0001_initial'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smslog',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_logs', to='scheduling.appointment', verbose_name='การนัดหมาย'),
        ),
        migrations.AddField(
            model_name='smslog',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sms_logs', to='clinics.clinic', verbose_name='สาขา'),
        ),
        migrations.AddField(
            model_name='smslog',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sms_logs', to='patients.patient', verbose_name='คนไข้'),
        ),
        migrations.AddIndex(
            model_name='smslog',
            index=models.Index(fields=['clinic', '-created_at'], name='notificatio_clinic__075aec_idx'),
        ),
        migrations.AddConstraint(
            model_name='smslog',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'failed'), _negated=True), fields=('appointment', 'kind'), name='sms_unique_reminder_per_appointment'),
        ),
    ]
