# Generated by Django 5.2.17 on 2026-08-12 13:39

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขล่าสุดเมื่อ')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='ชื่อบริการ')),
                ('category', models.CharField(blank=True, db_index=True, max_length=80, verbose_name='หมวดหมู่')),
                ('description', models.TextField(blank=True, verbose_name='รายละเอียด')),
                ('duration_minutes', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(600)], verbose_name='ระยะเวลาที่ใช้ (นาที)')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='ราคา (บาท)')),
                ('requires_doctor', models.BooleanField(default=True, help_text='ถ้าไม่ต้องใช้แพทย์ ระบบจะจำกัดคิวด้วยเพดานของสาขาแทนตารางแพทย์', verbose_name='ต้องมีแพทย์')),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดให้จอง')),
            ],
            options={
                'verbose_name': 'ประเภทบริการ',
                'verbose_name_plural': 'ประเภทบริการ',
                'ordering': ['category', 'name'],
            },
        ),
    ]
