# Generated by Django 5.2.17 on 2026-08-12 13:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขล่าสุดเมื่อ')),
                ('name', models.CharField(max_length=150, verbose_name='ชื่อสาขา')),
                ('code', models.CharField(help_text='ใช้เป็น prefix ของรหัสคนไข้ เช่น BKK', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='รหัสสาขาใช้ได้เฉพาะ A-Z, 0-9 และ - ความยาว 2-20 ตัวอักษร', regex='^[A-Z0-9\\-]{2,20}$')], verbose_name='รหัสสาขา')),
                ('address', models.TextField(blank=True, verbose_name='ที่อยู่')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='เบอร์โทรสาขา')),
                ('opening_time', models.TimeField(verbose_name='เวลาเปิดทำการ')),
                ('closing_time', models.TimeField(verbose_name='เวลาปิดทำการ')),
                ('timezone', models.CharField(default='Asia/Bangkok', help_text='ใช้แปลงเวลาที่เก็บเป็น UTC ในฐานข้อมูลให้เป็นเวลาท้องถิ่นของสาขา', max_length=64, verbose_name='โซนเวลา')),
                ('slot_interval_minutes', models.PositiveSmallIntegerField(default=15, help_text='ระบบจะเสนอเวลาเริ่มคิวเป็นช่วง ๆ ตามค่านี้ เช่น ทุก 15 นาที', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(120)], verbose_name='ความละเอียดของตารางคิว (นาที)')),
                ('non_doctor_service_capacity', models.PositiveSmallIntegerField(default=1, help_text='ใช้เป็นเพดานกันการรับคิวเกินกำลังของสาขาสำหรับบริการที่ไม่ต้องใช้แพทย์', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='จำนวนเคสพร้อมกันสูงสุดของบริการที่ไม่ต้องมีแพทย์')),
                ('sms_provider', models.CharField(choices=[('default', 'ใช้ค่าเริ่มต้นของระบบ'), ('console', 'เขียนลง log (สำหรับพัฒนา)'), ('thaibulksms', 'Thai Bulk SMS'), ('twilio', 'Twilio')], default='default', max_length=20, verbose_name='ผู้ให้บริการ SMS')),
                ('sms_sender_name', models.CharField(blank=True, help_text='ชื่อที่แสดงเป็นผู้ส่งข้อความ (ตามที่ลงทะเบียนไว้กับผู้ให้บริการ)', max_length=20, verbose_name='ชื่อผู้ส่ง SMS')),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดใช้งาน')),
            ],
            options={
                'verbose_name': 'สาขา',
                'verbose_name_plural': 'สาขา',
                'ordering': ['name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('closing_time__gt', models.F('opening_time'))), name='clinic_closing_time_after_opening_time')],
            },
        ),
    ]
