# Generated by Django 5.2.17 on 2026-08-12 13:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขล่าสุดเมื่อ')),
                ('note_text', models.TextField(verbose_name='บันทึก')),
                ('is_pinned', models.BooleanField(default=False, help_text='โน้ตสำคัญที่ต้องเห็นทุกครั้งที่เปิดคิวคนไข้ เช่น ประวัติแพ้ยา', verbose_name='ปักหมุด')),
            ],
            options={
                'verbose_name': 'โน้ตคนไข้',
                'verbose_name_plural': 'โน้ตคนไข้',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขล่าสุดเมื่อ')),
                ('patient_code', models.CharField(db_index=True, help_text='ระบบสร้างให้อัตโนมัติ เช่น BKK-000123', max_length=20, unique=True, verbose_name='รหัสคนไข้')),
                ('first_name', models.CharField(max_length=100, verbose_name='ชื่อ')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='นามสกุล')),
                ('phone', models.CharField(db_index=True, max_length=10, validators=[django.core.validators.RegexValidator(message='เบอร์โทรต้องเป็นตัวเลข 9-10 หลักและขึ้นต้นด้วย 0 (เช่น 0812345678)', regex='^0\\d{8,9}$')], verbose_name='เบอร์โทร')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='วันเกิด')),
                ('gender', models.CharField(choices=[('female', 'หญิง'), ('male', 'ชาย'), ('other', 'อื่น ๆ'), ('unspecified', 'ไม่ระบุ')], default='unspecified', max_length=15, verbose_name='เพศ')),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดใช้งาน')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='สร้างโดย')),
                ('home_clinic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registered_patients', to='clinics.clinic', verbose_name='สาขาที่ลงทะเบียน')),
            ],
            options={
                'verbose_name': 'คนไข้',
                'verbose_name_plural': 'คนไข้',
                'ordering': ['-created_at'],
            },
        ),
    ]
