# Generated by Django 5.2.17 on 2026-08-12 13:39

import apps.accounts.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='อีเมล')),
                ('full_name', models.CharField(max_length=150, verbose_name='ชื่อ-สกุล')),
                ('phone', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='เบอร์โทรต้องเป็นตัวเลข 9-10 หลักและขึ้นต้นด้วย 0 (เช่น 0812345678)', regex='^0\\d{8,9}$')], verbose_name='เบอร์โทร')),
                ('role', models.CharField(choices=[('super_admin', 'ผู้ดูแลระบบสูงสุด'), ('admin', 'ผู้จัดการสาขา'), ('staff', 'เจ้าหน้าที่หน้าเคาน์เตอร์'), ('doctor', 'แพทย์')], db_index=True, default='staff', max_length=20, verbose_name='บทบาท')),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดใช้งาน')),
                ('is_staff', models.BooleanField(default=False, verbose_name='เข้าหน้า Django admin ได้')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='เข้าร่วมเมื่อ')),
                ('clinic', models.ForeignKey(blank=True, help_text='Super Admin ปล่อยว่างได้ (ดูแลทุกสาขา) role อื่นต้องระบุสาขา', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='clinics.clinic', verbose_name='สาขาที่สังกัด')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'ผู้ใช้งาน',
                'verbose_name_plural': 'ผู้ใช้งาน',
                'ordering': ['full_name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('role', 'super_admin'), ('clinic__isnull', False), _connector='OR'), name='user_non_super_admin_requires_clinic')],
            },
            managers=[
                ('objects', apps.accounts.models.UserManager()),
            ],
        ),
    ]
