--
-- PostgreSQL database dump
--


-- Dumped from database version 18.4
-- Dumped by pg_dump version 18.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: btree_gist; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS btree_gist WITH SCHEMA public;


--
-- Name: EXTENSION btree_gist; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION btree_gist IS 'support for indexing common datatypes in GiST';


--
-- Name: pg_trgm; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS pg_trgm WITH SCHEMA public;


--
-- Name: EXTENSION pg_trgm; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION pg_trgm IS 'text similarity measurement and index searching based on trigrams';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: accounts_user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.accounts_user (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    email character varying(254) NOT NULL,
    full_name character varying(150) NOT NULL,
    phone character varying(10) NOT NULL,
    role character varying(20) NOT NULL,
    is_active boolean NOT NULL,
    is_staff boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    clinic_id bigint,
    CONSTRAINT user_non_super_admin_requires_clinic CHECK ((((role)::text = 'super_admin'::text) OR (clinic_id IS NOT NULL)))
);


--
-- Name: accounts_user_groups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.accounts_user_groups (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    group_id integer NOT NULL
);


--
-- Name: accounts_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.accounts_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.accounts_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_user_user_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.accounts_user_user_permissions (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: accounts_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.accounts_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: clinics_clinic; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.clinics_clinic (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    name character varying(150) NOT NULL,
    code character varying(20) NOT NULL,
    address text NOT NULL,
    phone character varying(20) NOT NULL,
    opening_time time without time zone NOT NULL,
    closing_time time without time zone NOT NULL,
    timezone character varying(64) NOT NULL,
    slot_interval_minutes smallint NOT NULL,
    non_doctor_service_capacity smallint NOT NULL,
    sms_provider character varying(20) NOT NULL,
    sms_sender_name character varying(20) NOT NULL,
    is_active boolean NOT NULL,
    CONSTRAINT clinic_closing_time_after_opening_time CHECK ((closing_time > opening_time)),
    CONSTRAINT clinics_clinic_non_doctor_service_capacity_check CHECK ((non_doctor_service_capacity >= 0)),
    CONSTRAINT clinics_clinic_slot_interval_minutes_check CHECK ((slot_interval_minutes >= 0))
);


--
-- Name: clinics_clinic_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.clinics_clinic ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.clinics_clinic_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


--
-- Name: doctors_doctor; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.doctors_doctor (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    display_name character varying(150) NOT NULL,
    specialties character varying(255) NOT NULL,
    color character varying(7) NOT NULL,
    is_active boolean NOT NULL,
    clinic_id bigint NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: doctors_doctor_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.doctors_doctor ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.doctors_doctor_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: doctors_doctorschedule; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.doctors_doctorschedule (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    day_of_week smallint NOT NULL,
    start_time time without time zone NOT NULL,
    end_time time without time zone NOT NULL,
    is_active boolean NOT NULL,
    clinic_id bigint NOT NULL,
    doctor_id bigint NOT NULL,
    CONSTRAINT doctor_schedule_end_after_start CHECK ((end_time > start_time)),
    CONSTRAINT doctors_doctorschedule_day_of_week_check CHECK ((day_of_week >= 0))
);


--
-- Name: doctors_doctorschedule_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.doctors_doctorschedule ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.doctors_doctorschedule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: doctors_timeblock; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.doctors_timeblock (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    start_datetime timestamp with time zone NOT NULL,
    end_datetime timestamp with time zone NOT NULL,
    reason character varying(20) NOT NULL,
    note character varying(255) NOT NULL,
    is_recurring boolean NOT NULL,
    recurrence character varying(10) NOT NULL,
    recurrence_end_date date,
    clinic_id bigint NOT NULL,
    doctor_id bigint NOT NULL,
    CONSTRAINT time_block_end_after_start CHECK ((end_datetime > start_datetime))
);


--
-- Name: doctors_timeblock_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.doctors_timeblock ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.doctors_timeblock_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notifications_smslog; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notifications_smslog (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    kind character varying(30) NOT NULL,
    message text NOT NULL,
    status character varying(10) NOT NULL,
    provider character varying(20) NOT NULL,
    provider_message_id character varying(100) NOT NULL,
    error_message character varying(255) NOT NULL,
    sent_at timestamp with time zone,
    appointment_id bigint,
    clinic_id bigint NOT NULL,
    patient_id bigint NOT NULL
);


--
-- Name: notifications_smslog_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.notifications_smslog ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notifications_smslog_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: patients_patient; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.patients_patient (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    patient_code character varying(20) NOT NULL,
    first_name character varying(100) NOT NULL,
    last_name character varying(100) NOT NULL,
    phone character varying(10) NOT NULL,
    date_of_birth date,
    gender character varying(15) NOT NULL,
    is_active boolean NOT NULL,
    created_by_id bigint,
    home_clinic_id bigint NOT NULL
);


--
-- Name: patients_patient_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.patients_patient ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.patients_patient_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: patients_patientnote; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.patients_patientnote (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    note_text text NOT NULL,
    is_pinned boolean NOT NULL,
    appointment_id bigint,
    created_by_id bigint,
    patient_id bigint NOT NULL
);


--
-- Name: patients_patientnote_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.patients_patientnote ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.patients_patientnote_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: scheduling_appointment; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.scheduling_appointment (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    scheduled_start timestamp with time zone NOT NULL,
    scheduled_end timestamp with time zone NOT NULL,
    status character varying(15) NOT NULL,
    source character varying(15) NOT NULL,
    note character varying(255) NOT NULL,
    checked_in_at timestamp with time zone,
    started_at timestamp with time zone,
    completed_at timestamp with time zone,
    cancelled_reason character varying(255) NOT NULL,
    clinic_id bigint NOT NULL,
    created_by_id bigint,
    doctor_id bigint,
    patient_id bigint NOT NULL,
    service_type_id bigint NOT NULL,
    CONSTRAINT appointment_end_after_start CHECK ((scheduled_end > scheduled_start))
);


--
-- Name: scheduling_appointment_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.scheduling_appointment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.scheduling_appointment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: services_servicetype; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.services_servicetype (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    name character varying(150) NOT NULL,
    category character varying(80) NOT NULL,
    description text NOT NULL,
    duration_minutes smallint NOT NULL,
    price numeric(10,2) NOT NULL,
    requires_doctor boolean NOT NULL,
    is_active boolean NOT NULL,
    CONSTRAINT services_servicetype_duration_minutes_check CHECK ((duration_minutes >= 0))
);


--
-- Name: services_servicetype_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.services_servicetype ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.services_servicetype_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: token_blacklist_blacklistedtoken; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.token_blacklist_blacklistedtoken (
    id bigint NOT NULL,
    blacklisted_at timestamp with time zone NOT NULL,
    token_id bigint NOT NULL
);


--
-- Name: token_blacklist_blacklistedtoken_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.token_blacklist_blacklistedtoken ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.token_blacklist_blacklistedtoken_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: token_blacklist_outstandingtoken; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.token_blacklist_outstandingtoken (
    id bigint NOT NULL,
    token text NOT NULL,
    created_at timestamp with time zone,
    expires_at timestamp with time zone NOT NULL,
    user_id bigint,
    jti character varying(255) CONSTRAINT token_blacklist_outstandingtoken_jti_hex_not_null NOT NULL
);


--
-- Name: token_blacklist_outstandingtoken_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.token_blacklist_outstandingtoken ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.token_blacklist_outstandingtoken_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: accounts_user; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.accounts_user (id, password, last_login, is_superuser, email, full_name, phone, role, is_active, is_staff, date_joined, clinic_id) VALUES (1, 'pbkdf2_sha256$1000000$ifLzdKhyR9mpsKEmtNH9xa$LlwfPcAfPj5C+LFw6Hw+yLZBDE+G2HfnVLkN4mNqhsw=', NULL, true, 'root@clinic.test', 'ผู้ดูแลระบบ', '', 'super_admin', true, true, '2026-08-15 00:13:42.778323+07', NULL);
INSERT INTO public.accounts_user (id, password, last_login, is_superuser, email, full_name, phone, role, is_active, is_staff, date_joined, clinic_id) VALUES (2, 'pbkdf2_sha256$1000000$gRCoivDKSlQtUMefW3ckBo$FdXl1vvI/tcqxXEbS8jQuA9C+AU8g/ZJE7jXnSxbGpk=', NULL, false, 'admin.bkk@clinic.test', 'ผู้จัดการ คลินิกสาขาสุขุมวิท', '', 'admin', true, false, '2026-08-15 00:13:43.173562+07', 1);
INSERT INTO public.accounts_user (id, password, last_login, is_superuser, email, full_name, phone, role, is_active, is_staff, date_joined, clinic_id) VALUES (3, 'pbkdf2_sha256$1000000$xkXBbzLsgWApiF8CWTReW5$Lc4Ha0FPIsvDOmAPzgRou21Zati52CggZiPrPQ68EbY=', NULL, false, 'staff.bkk@clinic.test', 'เจ้าหน้าที่ คลินิกสาขาสุขุมวิท', '', 'staff', true, false, '2026-08-15 00:13:43.532786+07', 1);
INSERT INTO public.accounts_user (id, password, last_login, is_superuser, email, full_name, phone, role, is_active, is_staff, date_joined, clinic_id) VALUES (4, 'pbkdf2_sha256$1000000$rowpANZ0aCMoGLpOVThWjG$hDffqt+nUz3bzYbC3SaYBNbuy68OoUjXa5sRle8ZNUM=', NULL, false, 'admin.cnx@clinic.test', 'ผู้จัดการ คลินิกสาขาเชียงใหม่', '', 'admin', true, false, '2026-08-15 00:13:43.923382+07', 2);
INSERT INTO public.accounts_user (id, password, last_login, is_superuser, email, full_name, phone, role, is_active, is_staff, date_joined, clinic_id) VALUES (5, 'pbkdf2_sha256$1000000$ozNyNH2VFgXKIPInKWKwlT$YH3cRtG+wBPkp8BRxksheC0/Up2ZBrWVGAC5p+3Sc5A=', NULL, false, 'staff.cnx@clinic.test', 'เจ้าหน้าที่ คลินิกสาขาเชียงใหม่', '', 'staff', true, false, '2026-08-15 00:13:44.295881+07', 2);
INSERT INTO public.accounts_user (id, password, last_login, is_superuser, email, full_name, phone, role, is_active, is_staff, date_joined, clinic_id) VALUES (6, 'pbkdf2_sha256$1000000$T83j76UYewTozcrwFUvDgp$rM5VD5IIOY+0xEc2i6YGeeabpOrGKrVyJaGNvvgAAyQ=', NULL, false, 'doctor.ploy@clinic.test', 'พญ. พลอย รักษาดี', '', 'doctor', true, false, '2026-08-15 00:13:44.681401+07', 1);
INSERT INTO public.accounts_user (id, password, last_login, is_superuser, email, full_name, phone, role, is_active, is_staff, date_joined, clinic_id) VALUES (7, 'pbkdf2_sha256$1000000$luRWJ0MwdOoC6rtpaOVqGI$6zlSHeNEsqvmG7YDM6d5pi8fJ879vpUvQTwauyquKLk=', NULL, false, 'doctor.non@clinic.test', 'นพ. นนท์ ผิวใส', '', 'doctor', true, false, '2026-08-15 00:13:45.126697+07', 1);
INSERT INTO public.accounts_user (id, password, last_login, is_superuser, email, full_name, phone, role, is_active, is_staff, date_joined, clinic_id) VALUES (8, 'pbkdf2_sha256$1000000$bGnxbjM90Pteiatril9g6r$MZwneevFzT+TddEreQf1k6KUVl5CC7yVt28dcbG1HzE=', NULL, false, 'doctor.mint@clinic.test', 'พญ. มิ้นท์ ใจงาม', '', 'doctor', true, false, '2026-08-15 00:13:45.543817+07', 2);
INSERT INTO public.accounts_user (id, password, last_login, is_superuser, email, full_name, phone, role, is_active, is_staff, date_joined, clinic_id) VALUES (11, 'pbkdf2_sha256$1000000$cKgbAhU8a6gDDMGFNV6BJO$kH7XGvcfuxvstfUqIGokZgq5/fogUY+hUVWWxASSebM=', NULL, false, 'somjai@gmail.com', 'พญ.สมใจ ใจสม', '089999999', 'doctor', true, false, '2026-08-15 01:34:07.757563+07', 2);


--
-- Data for Name: accounts_user_groups; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: accounts_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (1, 'Can add log entry', 1, 'add_logentry');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (2, 'Can change log entry', 1, 'change_logentry');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (3, 'Can delete log entry', 1, 'delete_logentry');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (4, 'Can view log entry', 1, 'view_logentry');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (5, 'Can add permission', 2, 'add_permission');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (6, 'Can change permission', 2, 'change_permission');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (7, 'Can delete permission', 2, 'delete_permission');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (8, 'Can view permission', 2, 'view_permission');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (9, 'Can add group', 3, 'add_group');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (10, 'Can change group', 3, 'change_group');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (11, 'Can delete group', 3, 'delete_group');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (12, 'Can view group', 3, 'view_group');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (13, 'Can add content type', 4, 'add_contenttype');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (14, 'Can change content type', 4, 'change_contenttype');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (15, 'Can delete content type', 4, 'delete_contenttype');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (16, 'Can view content type', 4, 'view_contenttype');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (17, 'Can add session', 5, 'add_session');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (18, 'Can change session', 5, 'change_session');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (19, 'Can delete session', 5, 'delete_session');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (20, 'Can view session', 5, 'view_session');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (21, 'Can add Blacklisted Token', 6, 'add_blacklistedtoken');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (22, 'Can change Blacklisted Token', 6, 'change_blacklistedtoken');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (23, 'Can delete Blacklisted Token', 6, 'delete_blacklistedtoken');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (24, 'Can view Blacklisted Token', 6, 'view_blacklistedtoken');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (25, 'Can add Outstanding Token', 7, 'add_outstandingtoken');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (26, 'Can change Outstanding Token', 7, 'change_outstandingtoken');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (27, 'Can delete Outstanding Token', 7, 'delete_outstandingtoken');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (28, 'Can view Outstanding Token', 7, 'view_outstandingtoken');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (29, 'Can add ผู้ใช้งาน', 8, 'add_user');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (30, 'Can change ผู้ใช้งาน', 8, 'change_user');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (31, 'Can delete ผู้ใช้งาน', 8, 'delete_user');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (32, 'Can view ผู้ใช้งาน', 8, 'view_user');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (33, 'Can add สาขา', 9, 'add_clinic');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (34, 'Can change สาขา', 9, 'change_clinic');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (35, 'Can delete สาขา', 9, 'delete_clinic');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (36, 'Can view สาขา', 9, 'view_clinic');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (37, 'Can add แพทย์', 10, 'add_doctor');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (38, 'Can change แพทย์', 10, 'change_doctor');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (39, 'Can delete แพทย์', 10, 'delete_doctor');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (40, 'Can view แพทย์', 10, 'view_doctor');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (41, 'Can add ตารางออกตรวจ', 11, 'add_doctorschedule');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (42, 'Can change ตารางออกตรวจ', 11, 'change_doctorschedule');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (43, 'Can delete ตารางออกตรวจ', 11, 'delete_doctorschedule');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (44, 'Can view ตารางออกตรวจ', 11, 'view_doctorschedule');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (45, 'Can add ช่วงเวลาที่ถูกบล็อก', 12, 'add_timeblock');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (46, 'Can change ช่วงเวลาที่ถูกบล็อก', 12, 'change_timeblock');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (47, 'Can delete ช่วงเวลาที่ถูกบล็อก', 12, 'delete_timeblock');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (48, 'Can view ช่วงเวลาที่ถูกบล็อก', 12, 'view_timeblock');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (49, 'Can add ประเภทบริการ', 13, 'add_servicetype');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (50, 'Can change ประเภทบริการ', 13, 'change_servicetype');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (51, 'Can delete ประเภทบริการ', 13, 'delete_servicetype');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (52, 'Can view ประเภทบริการ', 13, 'view_servicetype');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (53, 'Can add การนัดหมาย', 14, 'add_appointment');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (54, 'Can change การนัดหมาย', 14, 'change_appointment');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (55, 'Can delete การนัดหมาย', 14, 'delete_appointment');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (56, 'Can view การนัดหมาย', 14, 'view_appointment');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (57, 'Can add โน้ตคนไข้', 15, 'add_patientnote');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (58, 'Can change โน้ตคนไข้', 15, 'change_patientnote');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (59, 'Can delete โน้ตคนไข้', 15, 'delete_patientnote');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (60, 'Can view โน้ตคนไข้', 15, 'view_patientnote');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (61, 'Can add คนไข้', 16, 'add_patient');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (62, 'Can change คนไข้', 16, 'change_patient');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (63, 'Can delete คนไข้', 16, 'delete_patient');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (64, 'Can view คนไข้', 16, 'view_patient');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (65, 'Can add บันทึกการส่ง SMS', 17, 'add_smslog');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (66, 'Can change บันทึกการส่ง SMS', 17, 'change_smslog');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (67, 'Can delete บันทึกการส่ง SMS', 17, 'delete_smslog');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (68, 'Can view บันทึกการส่ง SMS', 17, 'view_smslog');


--
-- Data for Name: clinics_clinic; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.clinics_clinic (id, created_at, updated_at, name, code, address, phone, opening_time, closing_time, timezone, slot_interval_minutes, non_doctor_service_capacity, sms_provider, sms_sender_name, is_active) VALUES (1, '2026-08-15 00:13:42.745454+07', '2026-08-15 00:13:42.745473+07', 'คลินิกสาขาสุขุมวิท', 'BKK', '123 ถนนสุขุมวิท กรุงเทพฯ', '021234567', '09:00:00', '19:00:00', 'Asia/Bangkok', 15, 1, 'default', '', true);
INSERT INTO public.clinics_clinic (id, created_at, updated_at, name, code, address, phone, opening_time, closing_time, timezone, slot_interval_minutes, non_doctor_service_capacity, sms_provider, sms_sender_name, is_active) VALUES (2, '2026-08-15 00:13:42.755411+07', '2026-08-15 00:13:42.755422+07', 'คลินิกสาขาเชียงใหม่', 'CNX', '45 ถนนนิมมานเหมินท์ เชียงใหม่', '052123456', '10:00:00', '18:00:00', 'Asia/Bangkok', 15, 1, 'default', '', true);


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.django_content_type (id, app_label, model) VALUES (1, 'admin', 'logentry');
INSERT INTO public.django_content_type (id, app_label, model) VALUES (2, 'auth', 'permission');
INSERT INTO public.django_content_type (id, app_label, model) VALUES (3, 'auth', 'group');
INSERT INTO public.django_content_type (id, app_label, model) VALUES (4, 'contenttypes', 'contenttype');
INSERT INTO public.django_content_type (id, app_label, model) VALUES (5, 'sessions', 'session');
INSERT INTO public.django_content_type (id, app_label, model) VALUES (6, 'token_blacklist', 'blacklistedtoken');
INSERT INTO public.django_content_type (id, app_label, model) VALUES (7, 'token_blacklist', 'outstandingtoken');
INSERT INTO public.django_content_type (id, app_label, model) VALUES (8, 'accounts', 'user');
INSERT INTO public.django_content_type (id, app_label, model) VALUES (9, 'clinics', 'clinic');
INSERT INTO public.django_content_type (id, app_label, model) VALUES (10, 'doctors', 'doctor');
INSERT INTO public.django_content_type (id, app_label, model) VALUES (11, 'doctors', 'doctorschedule');
INSERT INTO public.django_content_type (id, app_label, model) VALUES (12, 'doctors', 'timeblock');
INSERT INTO public.django_content_type (id, app_label, model) VALUES (13, 'services', 'servicetype');
INSERT INTO public.django_content_type (id, app_label, model) VALUES (14, 'scheduling', 'appointment');
INSERT INTO public.django_content_type (id, app_label, model) VALUES (15, 'patients', 'patientnote');
INSERT INTO public.django_content_type (id, app_label, model) VALUES (16, 'patients', 'patient');
INSERT INTO public.django_content_type (id, app_label, model) VALUES (17, 'notifications', 'smslog');


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.django_migrations (id, app, name, applied) VALUES (1, 'clinics', '0001_initial', '2026-08-13 22:06:20.763402+07');
INSERT INTO public.django_migrations (id, app, name, applied) VALUES (2, 'contenttypes', '0001_initial', '2026-08-13 22:06:20.773031+07');
INSERT INTO public.django_migrations (id, app, name, applied) VALUES (3, 'contenttypes', '0002_remove_content_type_name', '2026-08-13 22:06:20.78087+07');
INSERT INTO public.django_migrations (id, app, name, applied) VALUES (4, 'auth', '0001_initial', '2026-08-13 22:06:20.818786+07');
INSERT INTO public.django_migrations (id, app, name, applied) VALUES (5, 'auth', '0002_alter_permission_name_max_length', '2026-08-13 22:06:20.823853+07');
INSERT INTO public.django_migrations (id, app, name, applied) VALUES (6, 'auth', '0003_alter_user_email_max_length', '2026-08-13 22:06:20.827426+07');
INSERT INTO public.django_migrations (id, app, name, applied) VALUES (7, 'auth', '0004_alter_user_username_opts', '2026-08-13 22:06:20.831831+07');
INSERT INTO public.django_migrations (id, app, name, applied) VALUES (8, 'auth', '0005_alter_user_last_login_null', '2026-08-13 22:06:20.835656+07');
INSERT INTO public.django_migrations (id, app, name, applied) VALUES (9, 'auth', '0006_require_contenttypes_0002', '2026-08-13 22:06:20.836689+07');
INSERT INTO public.django_migrations (id, app, name, applied) VALUES (10, 'auth', '0007_alter_validators_add_error_messages', '2026-08-13 22:06:20.839374+07');
INSERT INTO public.django_migrations (id, app, name, applied) VALUES (11, 'auth', '0008_alter_user_username_max_length', '2026-08-13 22:06:20.842678+07');
INSERT INTO public.django_migrations (id, app, name, applied) VALUES (12, 'auth', '0009_alter_user_last_name_max_length', '2026-08-13 22:06:20.848516+07');
INSERT INTO public.django_migrations (id, app, name, applied) VALUES (13, 'auth', '0010_alter_group_name_max_length', '2026-08-13 22:06:20.855884+07');
INSERT INTO public.django_migrations (id, app, name, applied) VALUES (14, 'auth', '0011_update_proxy_permissions', '2026-08-13 22:06:20.860863+07');
INSERT INTO public.django_migrations (id, app, name, applied) VALUES (15, 'auth', '0012_alter_user_first_name_max_length', '2026-08-13 22:06:20.866137+07');
INSERT INTO public.django_migrations (id, app, name, applied) VALUES (16, 'accounts', '0001_initial', '2026-08-13 22:06:20.912685+07');
INSERT INTO public.django_migrations (id, app, name, applied) VALUES (17, 'admin', '0001_initial', '2026-08-13 22:06:20.928557+07');
INSERT INTO public.django_migrations (id, app, name, applied) VALUES (18, 'admin', '0002_logentry_remove_auto_add', '2026-08-13 22:06:20.934791+07');
INSERT INTO public.django_migrations (id, app, name, applied) VALUES (19, 'admin', '0003_logentry_add_action_flag_choices', '2026-08-13 22:06:20.940262+07');
INSERT INTO public.django_migrations (id, app, name, applied) VALUES (20, 'doctors', '0001_initial', '2026-08-13 22:06:21.027359+07');
INSERT INTO public.django_migrations (id, app, name, applied) VALUES (21, 'services', '0001_initial', '2026-08-13 22:06:21.040674+07');
INSERT INTO public.django_migrations (id, app, name, applied) VALUES (22, 'patients', '0001_initial', '2026-08-13 22:06:21.067902+07');
INSERT INTO public.django_migrations (id, app, name, applied) VALUES (23, 'scheduling', '0001_initial', '2026-08-13 22:06:21.105376+07');
INSERT INTO public.django_migrations (id, app, name, applied) VALUES (24, 'notifications', '0001_initial', '2026-08-13 22:06:21.115037+07');
INSERT INTO public.django_migrations (id, app, name, applied) VALUES (25, 'notifications', '0002_initial', '2026-08-13 22:06:21.165+07');
INSERT INTO public.django_migrations (id, app, name, applied) VALUES (26, 'patients', '0002_initial', '2026-08-13 22:06:21.273035+07');
INSERT INTO public.django_migrations (id, app, name, applied) VALUES (27, 'patients', '0003_patient_search_indexes', '2026-08-13 22:06:21.387164+07');
INSERT INTO public.django_migrations (id, app, name, applied) VALUES (28, 'scheduling', '0002_appointment_overlap_exclusion', '2026-08-13 22:06:21.533012+07');
INSERT INTO public.django_migrations (id, app, name, applied) VALUES (29, 'sessions', '0001_initial', '2026-08-13 22:06:21.547289+07');
INSERT INTO public.django_migrations (id, app, name, applied) VALUES (30, 'token_blacklist', '0001_initial', '2026-08-13 22:06:21.584605+07');
INSERT INTO public.django_migrations (id, app, name, applied) VALUES (31, 'token_blacklist', '0002_outstandingtoken_jti_hex', '2026-08-13 22:06:21.593016+07');
INSERT INTO public.django_migrations (id, app, name, applied) VALUES (32, 'token_blacklist', '0003_auto_20171017_2007', '2026-08-13 22:06:21.613628+07');
INSERT INTO public.django_migrations (id, app, name, applied) VALUES (33, 'token_blacklist', '0004_auto_20171017_2013', '2026-08-13 22:06:21.626235+07');
INSERT INTO public.django_migrations (id, app, name, applied) VALUES (34, 'token_blacklist', '0005_remove_outstandingtoken_jti', '2026-08-13 22:06:21.637192+07');
INSERT INTO public.django_migrations (id, app, name, applied) VALUES (35, 'token_blacklist', '0006_auto_20171017_2113', '2026-08-13 22:06:21.649697+07');
INSERT INTO public.django_migrations (id, app, name, applied) VALUES (36, 'token_blacklist', '0007_auto_20171017_2214', '2026-08-13 22:06:21.682393+07');
INSERT INTO public.django_migrations (id, app, name, applied) VALUES (37, 'token_blacklist', '0008_migrate_to_bigautofield', '2026-08-13 22:06:21.721787+07');
INSERT INTO public.django_migrations (id, app, name, applied) VALUES (38, 'token_blacklist', '0010_fix_migrate_to_bigautofield', '2026-08-13 22:06:21.744847+07');
INSERT INTO public.django_migrations (id, app, name, applied) VALUES (39, 'token_blacklist', '0011_linearizes_history', '2026-08-13 22:06:21.746396+07');
INSERT INTO public.django_migrations (id, app, name, applied) VALUES (40, 'token_blacklist', '0012_alter_outstandingtoken_user', '2026-08-13 22:06:21.758296+07');
INSERT INTO public.django_migrations (id, app, name, applied) VALUES (41, 'token_blacklist', '0013_alter_blacklistedtoken_options_and_more', '2026-08-13 22:06:21.76964+07');


--
-- Data for Name: doctors_doctor; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.doctors_doctor (id, created_at, updated_at, display_name, specialties, color, is_active, clinic_id, user_id) VALUES (1, '2026-08-15 00:13:45.063765+07', '2026-08-15 00:13:45.063776+07', 'พญ. พลอย รักษาดี', 'ผิวหนังและความงาม', '#2563eb', true, 1, 6);
INSERT INTO public.doctors_doctor (id, created_at, updated_at, display_name, specialties, color, is_active, clinic_id, user_id) VALUES (2, '2026-08-15 00:13:45.52706+07', '2026-08-15 00:13:45.527071+07', 'นพ. นนท์ ผิวใส', 'ผิวหนังและความงาม', '#16a34a', true, 1, 7);
INSERT INTO public.doctors_doctor (id, created_at, updated_at, display_name, specialties, color, is_active, clinic_id, user_id) VALUES (3, '2026-08-15 00:13:46.074861+07', '2026-08-15 00:13:46.074876+07', 'พญ. มิ้นท์ ใจงาม', 'ผิวหนังและความงาม', '#db2777', true, 2, 8);
INSERT INTO public.doctors_doctor (id, created_at, updated_at, display_name, specialties, color, is_active, clinic_id, user_id) VALUES (6, '2026-08-15 01:34:08.142124+07', '2026-08-15 01:34:08.142134+07', 'พญ.สมใจ', 'ผิวหนัง', '#0891b2', true, 2, 11);


--
-- Data for Name: doctors_doctorschedule; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.doctors_doctorschedule (id, created_at, updated_at, day_of_week, start_time, end_time, is_active, clinic_id, doctor_id) VALUES (1, '2026-08-15 00:13:45.077942+07', '2026-08-15 00:13:45.077953+07', 0, '09:00:00', '12:00:00', true, 1, 1);
INSERT INTO public.doctors_doctorschedule (id, created_at, updated_at, day_of_week, start_time, end_time, is_active, clinic_id, doctor_id) VALUES (2, '2026-08-15 00:13:45.083488+07', '2026-08-15 00:13:45.083497+07', 0, '13:00:00', '17:00:00', true, 1, 1);
INSERT INTO public.doctors_doctorschedule (id, created_at, updated_at, day_of_week, start_time, end_time, is_active, clinic_id, doctor_id) VALUES (3, '2026-08-15 00:13:45.084979+07', '2026-08-15 00:13:45.084988+07', 1, '09:00:00', '12:00:00', true, 1, 1);
INSERT INTO public.doctors_doctorschedule (id, created_at, updated_at, day_of_week, start_time, end_time, is_active, clinic_id, doctor_id) VALUES (4, '2026-08-15 00:13:45.088168+07', '2026-08-15 00:13:45.088182+07', 1, '13:00:00', '17:00:00', true, 1, 1);
INSERT INTO public.doctors_doctorschedule (id, created_at, updated_at, day_of_week, start_time, end_time, is_active, clinic_id, doctor_id) VALUES (5, '2026-08-15 00:13:45.090143+07', '2026-08-15 00:13:45.090152+07', 2, '09:00:00', '12:00:00', true, 1, 1);
INSERT INTO public.doctors_doctorschedule (id, created_at, updated_at, day_of_week, start_time, end_time, is_active, clinic_id, doctor_id) VALUES (6, '2026-08-15 00:13:45.091901+07', '2026-08-15 00:13:45.091913+07', 2, '13:00:00', '17:00:00', true, 1, 1);
INSERT INTO public.doctors_doctorschedule (id, created_at, updated_at, day_of_week, start_time, end_time, is_active, clinic_id, doctor_id) VALUES (7, '2026-08-15 00:13:45.095938+07', '2026-08-15 00:13:45.095948+07', 3, '09:00:00', '12:00:00', true, 1, 1);
INSERT INTO public.doctors_doctorschedule (id, created_at, updated_at, day_of_week, start_time, end_time, is_active, clinic_id, doctor_id) VALUES (8, '2026-08-15 00:13:45.097403+07', '2026-08-15 00:13:45.097411+07', 3, '13:00:00', '17:00:00', true, 1, 1);
INSERT INTO public.doctors_doctorschedule (id, created_at, updated_at, day_of_week, start_time, end_time, is_active, clinic_id, doctor_id) VALUES (9, '2026-08-15 00:13:45.098726+07', '2026-08-15 00:13:45.098733+07', 4, '09:00:00', '12:00:00', true, 1, 1);
INSERT INTO public.doctors_doctorschedule (id, created_at, updated_at, day_of_week, start_time, end_time, is_active, clinic_id, doctor_id) VALUES (10, '2026-08-15 00:13:45.101553+07', '2026-08-15 00:13:45.101565+07', 4, '13:00:00', '17:00:00', true, 1, 1);
INSERT INTO public.doctors_doctorschedule (id, created_at, updated_at, day_of_week, start_time, end_time, is_active, clinic_id, doctor_id) VALUES (11, '2026-08-15 00:13:45.528562+07', '2026-08-15 00:13:45.52857+07', 0, '09:00:00', '12:00:00', true, 1, 2);
INSERT INTO public.doctors_doctorschedule (id, created_at, updated_at, day_of_week, start_time, end_time, is_active, clinic_id, doctor_id) VALUES (12, '2026-08-15 00:13:45.530686+07', '2026-08-15 00:13:45.530743+07', 0, '13:00:00', '17:00:00', true, 1, 2);
INSERT INTO public.doctors_doctorschedule (id, created_at, updated_at, day_of_week, start_time, end_time, is_active, clinic_id, doctor_id) VALUES (13, '2026-08-15 00:13:45.532916+07', '2026-08-15 00:13:45.532925+07', 2, '09:00:00', '12:00:00', true, 1, 2);
INSERT INTO public.doctors_doctorschedule (id, created_at, updated_at, day_of_week, start_time, end_time, is_active, clinic_id, doctor_id) VALUES (14, '2026-08-15 00:13:45.534343+07', '2026-08-15 00:13:45.534351+07', 2, '13:00:00', '17:00:00', true, 1, 2);
INSERT INTO public.doctors_doctorschedule (id, created_at, updated_at, day_of_week, start_time, end_time, is_active, clinic_id, doctor_id) VALUES (15, '2026-08-15 00:13:45.535645+07', '2026-08-15 00:13:45.535651+07', 4, '09:00:00', '12:00:00', true, 1, 2);
INSERT INTO public.doctors_doctorschedule (id, created_at, updated_at, day_of_week, start_time, end_time, is_active, clinic_id, doctor_id) VALUES (16, '2026-08-15 00:13:45.536836+07', '2026-08-15 00:13:45.536842+07', 4, '13:00:00', '17:00:00', true, 1, 2);
INSERT INTO public.doctors_doctorschedule (id, created_at, updated_at, day_of_week, start_time, end_time, is_active, clinic_id, doctor_id) VALUES (17, '2026-08-15 00:13:45.540105+07', '2026-08-15 00:13:45.540114+07', 5, '09:00:00', '12:00:00', true, 1, 2);
INSERT INTO public.doctors_doctorschedule (id, created_at, updated_at, day_of_week, start_time, end_time, is_active, clinic_id, doctor_id) VALUES (18, '2026-08-15 00:13:45.541365+07', '2026-08-15 00:13:45.541372+07', 5, '13:00:00', '17:00:00', true, 1, 2);
INSERT INTO public.doctors_doctorschedule (id, created_at, updated_at, day_of_week, start_time, end_time, is_active, clinic_id, doctor_id) VALUES (19, '2026-08-15 00:13:46.07778+07', '2026-08-15 00:13:46.077794+07', 1, '09:00:00', '12:00:00', true, 2, 3);
INSERT INTO public.doctors_doctorschedule (id, created_at, updated_at, day_of_week, start_time, end_time, is_active, clinic_id, doctor_id) VALUES (20, '2026-08-15 00:13:46.080469+07', '2026-08-15 00:13:46.080482+07', 1, '13:00:00', '17:00:00', true, 2, 3);
INSERT INTO public.doctors_doctorschedule (id, created_at, updated_at, day_of_week, start_time, end_time, is_active, clinic_id, doctor_id) VALUES (21, '2026-08-15 00:13:46.082369+07', '2026-08-15 00:13:46.08238+07', 2, '09:00:00', '12:00:00', true, 2, 3);
INSERT INTO public.doctors_doctorschedule (id, created_at, updated_at, day_of_week, start_time, end_time, is_active, clinic_id, doctor_id) VALUES (22, '2026-08-15 00:13:46.084437+07', '2026-08-15 00:13:46.084447+07', 2, '13:00:00', '17:00:00', true, 2, 3);
INSERT INTO public.doctors_doctorschedule (id, created_at, updated_at, day_of_week, start_time, end_time, is_active, clinic_id, doctor_id) VALUES (23, '2026-08-15 00:13:46.086554+07', '2026-08-15 00:13:46.086564+07', 3, '09:00:00', '12:00:00', true, 2, 3);
INSERT INTO public.doctors_doctorschedule (id, created_at, updated_at, day_of_week, start_time, end_time, is_active, clinic_id, doctor_id) VALUES (24, '2026-08-15 00:13:46.087963+07', '2026-08-15 00:13:46.087972+07', 3, '13:00:00', '17:00:00', true, 2, 3);
INSERT INTO public.doctors_doctorschedule (id, created_at, updated_at, day_of_week, start_time, end_time, is_active, clinic_id, doctor_id) VALUES (25, '2026-08-15 00:13:46.089443+07', '2026-08-15 00:13:46.089452+07', 4, '09:00:00', '12:00:00', true, 2, 3);
INSERT INTO public.doctors_doctorschedule (id, created_at, updated_at, day_of_week, start_time, end_time, is_active, clinic_id, doctor_id) VALUES (26, '2026-08-15 00:13:46.091276+07', '2026-08-15 00:13:46.091287+07', 4, '13:00:00', '17:00:00', true, 2, 3);
INSERT INTO public.doctors_doctorschedule (id, created_at, updated_at, day_of_week, start_time, end_time, is_active, clinic_id, doctor_id) VALUES (27, '2026-08-15 00:13:46.093593+07', '2026-08-15 00:13:46.093605+07', 5, '09:00:00', '12:00:00', true, 2, 3);
INSERT INTO public.doctors_doctorschedule (id, created_at, updated_at, day_of_week, start_time, end_time, is_active, clinic_id, doctor_id) VALUES (28, '2026-08-15 00:13:46.095152+07', '2026-08-15 00:13:46.095162+07', 5, '13:00:00', '17:00:00', true, 2, 3);


--
-- Data for Name: doctors_timeblock; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.doctors_timeblock (id, created_at, updated_at, start_datetime, end_datetime, reason, note, is_recurring, recurrence, recurrence_end_date, clinic_id, doctor_id) VALUES (1, '2026-08-15 00:13:45.12373+07', '2026-08-15 00:13:45.123741+07', '2026-08-15 12:00:00+07', '2026-08-15 13:00:00+07', 'lunch', 'พักเที่ยงประจำวัน', true, 'daily', NULL, 1, 1);
INSERT INTO public.doctors_timeblock (id, created_at, updated_at, start_datetime, end_datetime, reason, note, is_recurring, recurrence, recurrence_end_date, clinic_id, doctor_id) VALUES (2, '2026-08-15 00:13:45.542552+07', '2026-08-15 00:13:45.542559+07', '2026-08-15 12:00:00+07', '2026-08-15 13:00:00+07', 'lunch', 'พักเที่ยงประจำวัน', true, 'daily', NULL, 1, 2);
INSERT INTO public.doctors_timeblock (id, created_at, updated_at, start_datetime, end_datetime, reason, note, is_recurring, recurrence, recurrence_end_date, clinic_id, doctor_id) VALUES (3, '2026-08-15 00:13:46.096342+07', '2026-08-15 00:13:46.096349+07', '2026-08-15 12:00:00+07', '2026-08-15 13:00:00+07', 'lunch', 'พักเที่ยงประจำวัน', true, 'daily', NULL, 2, 3);


--
-- Data for Name: notifications_smslog; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: patients_patient; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.patients_patient (id, created_at, updated_at, patient_code, first_name, last_name, phone, date_of_birth, gender, is_active, created_by_id, home_clinic_id) VALUES (1, '2026-08-15 00:13:46.152122+07', '2026-08-15 00:13:46.152134+07', 'BKK-000001', 'สมหญิง', 'ใจดี', '0811111111', NULL, 'unspecified', true, NULL, 1);
INSERT INTO public.patients_patient (id, created_at, updated_at, patient_code, first_name, last_name, phone, date_of_birth, gender, is_active, created_by_id, home_clinic_id) VALUES (2, '2026-08-15 00:13:46.160553+07', '2026-08-15 00:13:46.160563+07', 'BKK-000002', 'สมชาย', 'รักสุขภาพ', '0822222222', NULL, 'unspecified', true, NULL, 1);
INSERT INTO public.patients_patient (id, created_at, updated_at, patient_code, first_name, last_name, phone, date_of_birth, gender, is_active, created_by_id, home_clinic_id) VALUES (3, '2026-08-15 00:13:46.165096+07', '2026-08-15 00:13:46.165111+07', 'BKK-000003', 'ปรียา', 'แสงทอง', '0833333333', NULL, 'unspecified', true, NULL, 1);
INSERT INTO public.patients_patient (id, created_at, updated_at, patient_code, first_name, last_name, phone, date_of_birth, gender, is_active, created_by_id, home_clinic_id) VALUES (4, '2026-08-15 00:13:46.170556+07', '2026-08-15 00:13:46.170566+07', 'BKK-000004', 'วิชัย', 'มั่นคง', '0844444444', NULL, 'unspecified', true, NULL, 1);
INSERT INTO public.patients_patient (id, created_at, updated_at, patient_code, first_name, last_name, phone, date_of_birth, gender, is_active, created_by_id, home_clinic_id) VALUES (5, '2026-08-15 00:19:33.258299+07', '2026-08-15 00:19:33.25831+07', 'BKK-000005', 'พงศภัค', 'หลักไชย', '0994622397', '2002-01-30', 'male', true, 3, 1);


--
-- Data for Name: patients_patientnote; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: scheduling_appointment; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.scheduling_appointment (id, created_at, updated_at, scheduled_start, scheduled_end, status, source, note, checked_in_at, started_at, completed_at, cancelled_reason, clinic_id, created_by_id, doctor_id, patient_id, service_type_id) VALUES (1, '2026-08-15 00:20:04.346597+07', '2026-08-15 00:20:21.567728+07', '2026-08-15 09:15:00+07', '2026-08-15 10:15:00+07', 'no_show', 'staff_created', '', NULL, NULL, NULL, '', 1, 3, 2, 5, 3);
INSERT INTO public.scheduling_appointment (id, created_at, updated_at, scheduled_start, scheduled_end, status, source, note, checked_in_at, started_at, completed_at, cancelled_reason, clinic_id, created_by_id, doctor_id, patient_id, service_type_id) VALUES (5, '2026-08-15 00:27:58.968829+07', '2026-08-15 00:27:58.968838+07', '2026-08-17 09:00:00+07', '2026-08-17 09:30:00+07', 'booked', 'staff_created', '', NULL, NULL, NULL, '', 1, NULL, 1, 1, 1);
INSERT INTO public.scheduling_appointment (id, created_at, updated_at, scheduled_start, scheduled_end, status, source, note, checked_in_at, started_at, completed_at, cancelled_reason, clinic_id, created_by_id, doctor_id, patient_id, service_type_id) VALUES (6, '2026-08-15 00:27:58.97862+07', '2026-08-15 00:27:58.978627+07', '2026-08-17 10:00:00+07', '2026-08-17 10:30:00+07', 'booked', 'staff_created', '', NULL, NULL, NULL, '', 1, NULL, 1, 2, 1);
INSERT INTO public.scheduling_appointment (id, created_at, updated_at, scheduled_start, scheduled_end, status, source, note, checked_in_at, started_at, completed_at, cancelled_reason, clinic_id, created_by_id, doctor_id, patient_id, service_type_id) VALUES (7, '2026-08-15 00:27:58.986603+07', '2026-08-15 00:27:58.986613+07', '2026-08-17 11:00:00+07', '2026-08-17 11:30:00+07', 'booked', 'staff_created', '', NULL, NULL, NULL, '', 1, NULL, 1, 3, 1);
INSERT INTO public.scheduling_appointment (id, created_at, updated_at, scheduled_start, scheduled_end, status, source, note, checked_in_at, started_at, completed_at, cancelled_reason, clinic_id, created_by_id, doctor_id, patient_id, service_type_id) VALUES (8, '2026-08-15 00:27:58.994916+07', '2026-08-15 00:27:58.994925+07', '2026-08-17 13:15:00+07', '2026-08-17 13:45:00+07', 'booked', 'staff_created', '', NULL, NULL, NULL, '', 1, NULL, 1, 4, 1);


--
-- Data for Name: services_servicetype; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.services_servicetype (id, created_at, updated_at, name, category, description, duration_minutes, price, requires_doctor, is_active) VALUES (1, '2026-08-15 00:13:42.764181+07', '2026-08-15 00:13:42.764192+07', 'ฉีดโบลดริ้วรอย', 'ฉีด', '', 30, 8500.00, true, true);
INSERT INTO public.services_servicetype (id, created_at, updated_at, name, category, description, duration_minutes, price, requires_doctor, is_active) VALUES (2, '2026-08-15 00:13:42.769746+07', '2026-08-15 00:13:42.769756+07', 'ฟิลเลอร์ร่องแก้ม', 'ฉีด', '', 45, 12000.00, true, true);
INSERT INTO public.services_servicetype (id, created_at, updated_at, name, category, description, duration_minutes, price, requires_doctor, is_active) VALUES (3, '2026-08-15 00:13:42.770689+07', '2026-08-15 00:13:42.770696+07', 'เลเซอร์หน้าใส', 'เลเซอร์', '', 60, 3500.00, true, true);
INSERT INTO public.services_servicetype (id, created_at, updated_at, name, category, description, duration_minutes, price, requires_doctor, is_active) VALUES (4, '2026-08-15 00:13:42.771429+07', '2026-08-15 00:13:42.771435+07', 'ปรึกษาแพทย์', 'ปรึกษา', '', 15, 500.00, true, true);
INSERT INTO public.services_servicetype (id, created_at, updated_at, name, category, description, duration_minutes, price, requires_doctor, is_active) VALUES (5, '2026-08-15 00:13:42.772128+07', '2026-08-15 00:13:42.772133+07', 'ดริปวิตามินผิว', 'ดริป', '', 60, 2500.00, false, true);


--
-- Name: accounts_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.accounts_user_groups_id_seq', 1, false);


--
-- Name: accounts_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.accounts_user_id_seq', 11, true);


--
-- Name: accounts_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.accounts_user_user_permissions_id_seq', 1, false);


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 68, true);


--
-- Name: clinics_clinic_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.clinics_clinic_id_seq', 2, true);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 17, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 41, true);


--
-- Name: doctors_doctor_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.doctors_doctor_id_seq', 6, true);


--
-- Name: doctors_doctorschedule_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.doctors_doctorschedule_id_seq', 29, true);


--
-- Name: doctors_timeblock_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.doctors_timeblock_id_seq', 3, true);


--
-- Name: notifications_smslog_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.notifications_smslog_id_seq', 1, false);


--
-- Name: patients_patient_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.patients_patient_id_seq', 7, true);


--
-- Name: patients_patientnote_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.patients_patientnote_id_seq', 1, false);


--
-- Name: scheduling_appointment_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.scheduling_appointment_id_seq', 8, true);


--
-- Name: services_servicetype_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.services_servicetype_id_seq', 5, true);


--
-- Name: token_blacklist_blacklistedtoken_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.token_blacklist_blacklistedtoken_id_seq', 12, true);


--
-- Name: token_blacklist_outstandingtoken_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.token_blacklist_outstandingtoken_id_seq', 29, true);


--
-- Name: accounts_user accounts_user_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_user
    ADD CONSTRAINT accounts_user_email_key UNIQUE (email);


--
-- Name: accounts_user_groups accounts_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_pkey PRIMARY KEY (id);


--
-- Name: accounts_user_groups accounts_user_groups_user_id_group_id_59c0b32f_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_user_id_group_id_59c0b32f_uniq UNIQUE (user_id, group_id);


--
-- Name: accounts_user accounts_user_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_user
    ADD CONSTRAINT accounts_user_pkey PRIMARY KEY (id);


--
-- Name: accounts_user_user_permissions accounts_user_user_permi_user_id_permission_id_2ab516c2_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_permi_user_id_permission_id_2ab516c2_uniq UNIQUE (user_id, permission_id);


--
-- Name: accounts_user_user_permissions accounts_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: scheduling_appointment appointment_no_overlap_per_doctor; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scheduling_appointment
    ADD CONSTRAINT appointment_no_overlap_per_doctor EXCLUDE USING gist (doctor_id WITH =, tstzrange(scheduled_start, scheduled_end, '[)'::text) WITH &&) WHERE (((doctor_id IS NOT NULL) AND ((status)::text = ANY ((ARRAY['booked'::character varying, 'confirmed'::character varying, 'checked_in'::character varying, 'in_progress'::character varying, 'completed'::character varying])::text[]))));


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: clinics_clinic clinics_clinic_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.clinics_clinic
    ADD CONSTRAINT clinics_clinic_code_key UNIQUE (code);


--
-- Name: clinics_clinic clinics_clinic_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.clinics_clinic
    ADD CONSTRAINT clinics_clinic_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: doctors_doctorschedule doctor_schedule_unique_start_per_day; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.doctors_doctorschedule
    ADD CONSTRAINT doctor_schedule_unique_start_per_day UNIQUE (doctor_id, day_of_week, start_time);


--
-- Name: doctors_doctor doctors_doctor_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.doctors_doctor
    ADD CONSTRAINT doctors_doctor_pkey PRIMARY KEY (id);


--
-- Name: doctors_doctor doctors_doctor_user_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.doctors_doctor
    ADD CONSTRAINT doctors_doctor_user_id_key UNIQUE (user_id);


--
-- Name: doctors_doctorschedule doctors_doctorschedule_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.doctors_doctorschedule
    ADD CONSTRAINT doctors_doctorschedule_pkey PRIMARY KEY (id);


--
-- Name: doctors_timeblock doctors_timeblock_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.doctors_timeblock
    ADD CONSTRAINT doctors_timeblock_pkey PRIMARY KEY (id);


--
-- Name: notifications_smslog notifications_smslog_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications_smslog
    ADD CONSTRAINT notifications_smslog_pkey PRIMARY KEY (id);


--
-- Name: patients_patient patient_unique_phone_and_name; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.patients_patient
    ADD CONSTRAINT patient_unique_phone_and_name UNIQUE (phone, first_name, last_name);


--
-- Name: patients_patient patients_patient_patient_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.patients_patient
    ADD CONSTRAINT patients_patient_patient_code_key UNIQUE (patient_code);


--
-- Name: patients_patient patients_patient_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.patients_patient
    ADD CONSTRAINT patients_patient_pkey PRIMARY KEY (id);


--
-- Name: patients_patientnote patients_patientnote_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.patients_patientnote
    ADD CONSTRAINT patients_patientnote_pkey PRIMARY KEY (id);


--
-- Name: scheduling_appointment scheduling_appointment_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scheduling_appointment
    ADD CONSTRAINT scheduling_appointment_pkey PRIMARY KEY (id);


--
-- Name: services_servicetype services_servicetype_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.services_servicetype
    ADD CONSTRAINT services_servicetype_name_key UNIQUE (name);


--
-- Name: services_servicetype services_servicetype_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.services_servicetype
    ADD CONSTRAINT services_servicetype_pkey PRIMARY KEY (id);


--
-- Name: token_blacklist_blacklistedtoken token_blacklist_blacklistedtoken_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.token_blacklist_blacklistedtoken
    ADD CONSTRAINT token_blacklist_blacklistedtoken_pkey PRIMARY KEY (id);


--
-- Name: token_blacklist_blacklistedtoken token_blacklist_blacklistedtoken_token_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.token_blacklist_blacklistedtoken
    ADD CONSTRAINT token_blacklist_blacklistedtoken_token_id_key UNIQUE (token_id);


--
-- Name: token_blacklist_outstandingtoken token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.token_blacklist_outstandingtoken
    ADD CONSTRAINT token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_uniq UNIQUE (jti);


--
-- Name: token_blacklist_outstandingtoken token_blacklist_outstandingtoken_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.token_blacklist_outstandingtoken
    ADD CONSTRAINT token_blacklist_outstandingtoken_pkey PRIMARY KEY (id);


--
-- Name: accounts_user_clinic_id_07f9484b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounts_user_clinic_id_07f9484b ON public.accounts_user USING btree (clinic_id);


--
-- Name: accounts_user_email_b2644a56_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounts_user_email_b2644a56_like ON public.accounts_user USING btree (email varchar_pattern_ops);


--
-- Name: accounts_user_groups_group_id_bd11a704; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounts_user_groups_group_id_bd11a704 ON public.accounts_user_groups USING btree (group_id);


--
-- Name: accounts_user_groups_user_id_52b62117; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounts_user_groups_user_id_52b62117 ON public.accounts_user_groups USING btree (user_id);


--
-- Name: accounts_user_role_57e97df0; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounts_user_role_57e97df0 ON public.accounts_user USING btree (role);


--
-- Name: accounts_user_role_57e97df0_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounts_user_role_57e97df0_like ON public.accounts_user USING btree (role varchar_pattern_ops);


--
-- Name: accounts_user_user_permissions_permission_id_113bb443; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounts_user_user_permissions_permission_id_113bb443 ON public.accounts_user_user_permissions USING btree (permission_id);


--
-- Name: accounts_user_user_permissions_user_id_e4f0a161; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounts_user_user_permissions_user_id_e4f0a161 ON public.accounts_user_user_permissions USING btree (user_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: clinics_clinic_code_b3145a80_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX clinics_clinic_code_b3145a80_like ON public.clinics_clinic USING btree (code varchar_pattern_ops);


--
-- Name: clinics_clinic_created_at_f052ebc7; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX clinics_clinic_created_at_f052ebc7 ON public.clinics_clinic USING btree (created_at);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: doctors_doc_clinic__afa889_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX doctors_doc_clinic__afa889_idx ON public.doctors_doctor USING btree (clinic_id, is_active);


--
-- Name: doctors_doc_doctor__0d3163_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX doctors_doc_doctor__0d3163_idx ON public.doctors_doctorschedule USING btree (doctor_id, day_of_week, is_active);


--
-- Name: doctors_doctor_clinic_id_bb5df1a2; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX doctors_doctor_clinic_id_bb5df1a2 ON public.doctors_doctor USING btree (clinic_id);


--
-- Name: doctors_doctor_created_at_56590c26; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX doctors_doctor_created_at_56590c26 ON public.doctors_doctor USING btree (created_at);


--
-- Name: doctors_doctorschedule_clinic_id_990cc4dc; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX doctors_doctorschedule_clinic_id_990cc4dc ON public.doctors_doctorschedule USING btree (clinic_id);


--
-- Name: doctors_doctorschedule_created_at_21393ae6; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX doctors_doctorschedule_created_at_21393ae6 ON public.doctors_doctorschedule USING btree (created_at);


--
-- Name: doctors_doctorschedule_doctor_id_771dc8bf; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX doctors_doctorschedule_doctor_id_771dc8bf ON public.doctors_doctorschedule USING btree (doctor_id);


--
-- Name: doctors_tim_doctor__e70237_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX doctors_tim_doctor__e70237_idx ON public.doctors_timeblock USING btree (doctor_id, start_datetime);


--
-- Name: doctors_timeblock_clinic_id_4ba51446; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX doctors_timeblock_clinic_id_4ba51446 ON public.doctors_timeblock USING btree (clinic_id);


--
-- Name: doctors_timeblock_created_at_9f37c5e3; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX doctors_timeblock_created_at_9f37c5e3 ON public.doctors_timeblock USING btree (created_at);


--
-- Name: doctors_timeblock_doctor_id_ffb88657; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX doctors_timeblock_doctor_id_ffb88657 ON public.doctors_timeblock USING btree (doctor_id);


--
-- Name: doctors_timeblock_start_datetime_8e87a580; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX doctors_timeblock_start_datetime_8e87a580 ON public.doctors_timeblock USING btree (start_datetime);


--
-- Name: notificatio_clinic__075aec_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX notificatio_clinic__075aec_idx ON public.notifications_smslog USING btree (clinic_id, created_at DESC);


--
-- Name: notifications_smslog_appointment_id_6e1f71ab; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX notifications_smslog_appointment_id_6e1f71ab ON public.notifications_smslog USING btree (appointment_id);


--
-- Name: notifications_smslog_clinic_id_769a6acf; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX notifications_smslog_clinic_id_769a6acf ON public.notifications_smslog USING btree (clinic_id);


--
-- Name: notifications_smslog_created_at_2464a55a; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX notifications_smslog_created_at_2464a55a ON public.notifications_smslog USING btree (created_at);


--
-- Name: notifications_smslog_patient_id_07a00959; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX notifications_smslog_patient_id_07a00959 ON public.notifications_smslog USING btree (patient_id);


--
-- Name: notifications_smslog_status_308405b1; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX notifications_smslog_status_308405b1 ON public.notifications_smslog USING btree (status);


--
-- Name: notifications_smslog_status_308405b1_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX notifications_smslog_status_308405b1_like ON public.notifications_smslog USING btree (status varchar_pattern_ops);


--
-- Name: patient_first_name_trgm_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX patient_first_name_trgm_idx ON public.patients_patient USING gin (first_name public.gin_trgm_ops);


--
-- Name: patient_last_name_trgm_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX patient_last_name_trgm_idx ON public.patients_patient USING gin (last_name public.gin_trgm_ops);


--
-- Name: patients_pa_last_na_1b32a7_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX patients_pa_last_na_1b32a7_idx ON public.patients_patient USING btree (last_name, first_name);


--
-- Name: patients_pa_patient_5d5a3d_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX patients_pa_patient_5d5a3d_idx ON public.patients_patientnote USING btree (patient_id, created_at DESC);


--
-- Name: patients_pa_phone_fc49bb_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX patients_pa_phone_fc49bb_idx ON public.patients_patient USING btree (phone);


--
-- Name: patients_patient_created_at_a0dbdb93; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX patients_patient_created_at_a0dbdb93 ON public.patients_patient USING btree (created_at);


--
-- Name: patients_patient_created_by_id_cf506306; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX patients_patient_created_by_id_cf506306 ON public.patients_patient USING btree (created_by_id);


--
-- Name: patients_patient_home_clinic_id_368448cc; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX patients_patient_home_clinic_id_368448cc ON public.patients_patient USING btree (home_clinic_id);


--
-- Name: patients_patient_patient_code_9ce8008e_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX patients_patient_patient_code_9ce8008e_like ON public.patients_patient USING btree (patient_code varchar_pattern_ops);


--
-- Name: patients_patient_phone_1aab8710; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX patients_patient_phone_1aab8710 ON public.patients_patient USING btree (phone);


--
-- Name: patients_patient_phone_1aab8710_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX patients_patient_phone_1aab8710_like ON public.patients_patient USING btree (phone varchar_pattern_ops);


--
-- Name: patients_patientnote_appointment_id_c240add5; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX patients_patientnote_appointment_id_c240add5 ON public.patients_patientnote USING btree (appointment_id);


--
-- Name: patients_patientnote_created_at_b32ebbfc; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX patients_patientnote_created_at_b32ebbfc ON public.patients_patientnote USING btree (created_at);


--
-- Name: patients_patientnote_created_by_id_8d1b657c; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX patients_patientnote_created_by_id_8d1b657c ON public.patients_patientnote USING btree (created_by_id);


--
-- Name: patients_patientnote_patient_id_d72251b5; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX patients_patientnote_patient_id_d72251b5 ON public.patients_patientnote USING btree (patient_id);


--
-- Name: scheduling__clinic__465355_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX scheduling__clinic__465355_idx ON public.scheduling_appointment USING btree (clinic_id, scheduled_start);


--
-- Name: scheduling__doctor__7f4bc3_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX scheduling__doctor__7f4bc3_idx ON public.scheduling_appointment USING btree (doctor_id, scheduled_start);


--
-- Name: scheduling__status_30cd1b_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX scheduling__status_30cd1b_idx ON public.scheduling_appointment USING btree (status, scheduled_start);


--
-- Name: scheduling_appointment_clinic_id_c959ca14; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX scheduling_appointment_clinic_id_c959ca14 ON public.scheduling_appointment USING btree (clinic_id);


--
-- Name: scheduling_appointment_created_at_28aa4b7f; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX scheduling_appointment_created_at_28aa4b7f ON public.scheduling_appointment USING btree (created_at);


--
-- Name: scheduling_appointment_created_by_id_d7658cc7; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX scheduling_appointment_created_by_id_d7658cc7 ON public.scheduling_appointment USING btree (created_by_id);


--
-- Name: scheduling_appointment_doctor_id_ffd54d9a; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX scheduling_appointment_doctor_id_ffd54d9a ON public.scheduling_appointment USING btree (doctor_id);


--
-- Name: scheduling_appointment_patient_id_1a2fb708; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX scheduling_appointment_patient_id_1a2fb708 ON public.scheduling_appointment USING btree (patient_id);


--
-- Name: scheduling_appointment_scheduled_start_1f587c43; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX scheduling_appointment_scheduled_start_1f587c43 ON public.scheduling_appointment USING btree (scheduled_start);


--
-- Name: scheduling_appointment_service_type_id_37395baf; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX scheduling_appointment_service_type_id_37395baf ON public.scheduling_appointment USING btree (service_type_id);


--
-- Name: scheduling_appointment_status_a91a2fc6; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX scheduling_appointment_status_a91a2fc6 ON public.scheduling_appointment USING btree (status);


--
-- Name: scheduling_appointment_status_a91a2fc6_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX scheduling_appointment_status_a91a2fc6_like ON public.scheduling_appointment USING btree (status varchar_pattern_ops);


--
-- Name: services_servicetype_category_ce15c43f; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX services_servicetype_category_ce15c43f ON public.services_servicetype USING btree (category);


--
-- Name: services_servicetype_category_ce15c43f_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX services_servicetype_category_ce15c43f_like ON public.services_servicetype USING btree (category varchar_pattern_ops);


--
-- Name: services_servicetype_created_at_b1d792c2; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX services_servicetype_created_at_b1d792c2 ON public.services_servicetype USING btree (created_at);


--
-- Name: services_servicetype_name_e9c9b36d_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX services_servicetype_name_e9c9b36d_like ON public.services_servicetype USING btree (name varchar_pattern_ops);


--
-- Name: sms_unique_reminder_per_appointment; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX sms_unique_reminder_per_appointment ON public.notifications_smslog USING btree (appointment_id, kind) WHERE (NOT ((status)::text = 'failed'::text));


--
-- Name: token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_like ON public.token_blacklist_outstandingtoken USING btree (jti varchar_pattern_ops);


--
-- Name: token_blacklist_outstandingtoken_user_id_83bc629a; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX token_blacklist_outstandingtoken_user_id_83bc629a ON public.token_blacklist_outstandingtoken USING btree (user_id);


--
-- Name: accounts_user accounts_user_clinic_id_07f9484b_fk_clinics_clinic_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_user
    ADD CONSTRAINT accounts_user_clinic_id_07f9484b_fk_clinics_clinic_id FOREIGN KEY (clinic_id) REFERENCES public.clinics_clinic(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_user_groups accounts_user_groups_group_id_bd11a704_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_group_id_bd11a704_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_user_groups accounts_user_groups_user_id_52b62117_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_user_id_52b62117_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_user_user_permissions accounts_user_user_p_permission_id_113bb443_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_p_permission_id_113bb443_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_user_user_permissions accounts_user_user_p_user_id_e4f0a161_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_p_user_id_e4f0a161_fk_accounts_ FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: doctors_doctor doctors_doctor_clinic_id_bb5df1a2_fk_clinics_clinic_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.doctors_doctor
    ADD CONSTRAINT doctors_doctor_clinic_id_bb5df1a2_fk_clinics_clinic_id FOREIGN KEY (clinic_id) REFERENCES public.clinics_clinic(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: doctors_doctor doctors_doctor_user_id_c371de6c_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.doctors_doctor
    ADD CONSTRAINT doctors_doctor_user_id_c371de6c_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: doctors_doctorschedule doctors_doctorschedule_clinic_id_990cc4dc_fk_clinics_clinic_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.doctors_doctorschedule
    ADD CONSTRAINT doctors_doctorschedule_clinic_id_990cc4dc_fk_clinics_clinic_id FOREIGN KEY (clinic_id) REFERENCES public.clinics_clinic(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: doctors_doctorschedule doctors_doctorschedule_doctor_id_771dc8bf_fk_doctors_doctor_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.doctors_doctorschedule
    ADD CONSTRAINT doctors_doctorschedule_doctor_id_771dc8bf_fk_doctors_doctor_id FOREIGN KEY (doctor_id) REFERENCES public.doctors_doctor(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: doctors_timeblock doctors_timeblock_clinic_id_4ba51446_fk_clinics_clinic_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.doctors_timeblock
    ADD CONSTRAINT doctors_timeblock_clinic_id_4ba51446_fk_clinics_clinic_id FOREIGN KEY (clinic_id) REFERENCES public.clinics_clinic(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: doctors_timeblock doctors_timeblock_doctor_id_ffb88657_fk_doctors_doctor_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.doctors_timeblock
    ADD CONSTRAINT doctors_timeblock_doctor_id_ffb88657_fk_doctors_doctor_id FOREIGN KEY (doctor_id) REFERENCES public.doctors_doctor(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: notifications_smslog notifications_smslog_appointment_id_6e1f71ab_fk_schedulin; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications_smslog
    ADD CONSTRAINT notifications_smslog_appointment_id_6e1f71ab_fk_schedulin FOREIGN KEY (appointment_id) REFERENCES public.scheduling_appointment(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: notifications_smslog notifications_smslog_clinic_id_769a6acf_fk_clinics_clinic_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications_smslog
    ADD CONSTRAINT notifications_smslog_clinic_id_769a6acf_fk_clinics_clinic_id FOREIGN KEY (clinic_id) REFERENCES public.clinics_clinic(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: notifications_smslog notifications_smslog_patient_id_07a00959_fk_patients_patient_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications_smslog
    ADD CONSTRAINT notifications_smslog_patient_id_07a00959_fk_patients_patient_id FOREIGN KEY (patient_id) REFERENCES public.patients_patient(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: patients_patient patients_patient_created_by_id_cf506306_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.patients_patient
    ADD CONSTRAINT patients_patient_created_by_id_cf506306_fk_accounts_user_id FOREIGN KEY (created_by_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: patients_patient patients_patient_home_clinic_id_368448cc_fk_clinics_clinic_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.patients_patient
    ADD CONSTRAINT patients_patient_home_clinic_id_368448cc_fk_clinics_clinic_id FOREIGN KEY (home_clinic_id) REFERENCES public.clinics_clinic(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: patients_patientnote patients_patientnote_appointment_id_c240add5_fk_schedulin; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.patients_patientnote
    ADD CONSTRAINT patients_patientnote_appointment_id_c240add5_fk_schedulin FOREIGN KEY (appointment_id) REFERENCES public.scheduling_appointment(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: patients_patientnote patients_patientnote_created_by_id_8d1b657c_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.patients_patientnote
    ADD CONSTRAINT patients_patientnote_created_by_id_8d1b657c_fk_accounts_user_id FOREIGN KEY (created_by_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: patients_patientnote patients_patientnote_patient_id_d72251b5_fk_patients_patient_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.patients_patientnote
    ADD CONSTRAINT patients_patientnote_patient_id_d72251b5_fk_patients_patient_id FOREIGN KEY (patient_id) REFERENCES public.patients_patient(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: scheduling_appointment scheduling_appointme_created_by_id_d7658cc7_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scheduling_appointment
    ADD CONSTRAINT scheduling_appointme_created_by_id_d7658cc7_fk_accounts_ FOREIGN KEY (created_by_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: scheduling_appointment scheduling_appointme_patient_id_1a2fb708_fk_patients_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scheduling_appointment
    ADD CONSTRAINT scheduling_appointme_patient_id_1a2fb708_fk_patients_ FOREIGN KEY (patient_id) REFERENCES public.patients_patient(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: scheduling_appointment scheduling_appointme_service_type_id_37395baf_fk_services_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scheduling_appointment
    ADD CONSTRAINT scheduling_appointme_service_type_id_37395baf_fk_services_ FOREIGN KEY (service_type_id) REFERENCES public.services_servicetype(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: scheduling_appointment scheduling_appointment_clinic_id_c959ca14_fk_clinics_clinic_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scheduling_appointment
    ADD CONSTRAINT scheduling_appointment_clinic_id_c959ca14_fk_clinics_clinic_id FOREIGN KEY (clinic_id) REFERENCES public.clinics_clinic(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: scheduling_appointment scheduling_appointment_doctor_id_ffd54d9a_fk_doctors_doctor_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scheduling_appointment
    ADD CONSTRAINT scheduling_appointment_doctor_id_ffd54d9a_fk_doctors_doctor_id FOREIGN KEY (doctor_id) REFERENCES public.doctors_doctor(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: token_blacklist_blacklistedtoken token_blacklist_blacklistedtoken_token_id_3cc7fe56_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.token_blacklist_blacklistedtoken
    ADD CONSTRAINT token_blacklist_blacklistedtoken_token_id_3cc7fe56_fk FOREIGN KEY (token_id) REFERENCES public.token_blacklist_outstandingtoken(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: token_blacklist_outstandingtoken token_blacklist_outs_user_id_83bc629a_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.token_blacklist_outstandingtoken
    ADD CONSTRAINT token_blacklist_outs_user_id_83bc629a_fk_accounts_ FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--


