# Generated by Django 5.2.17 on 2026-08-12 13:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขล่าสุดเมื่อ')),
                ('display_name', models.CharField(max_length=150, verbose_name='ชื่อที่แสดง')),
                ('specialties', models.CharField(blank=True, max_length=255, verbose_name='ความเชี่ยวชาญ')),
                ('color', models.CharField(default='#2563eb', max_length=7, validators=[django.core.validators.RegexValidator(message='ต้องเป็นรหัสสีแบบ hex เช่น #2563eb', regex='^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$')], verbose_name='สีในปฏิทิน')),
                ('is_active', models.BooleanField(default=True, verbose_name='ออกตรวจอยู่')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doctors', to='clinics.clinic', verbose_name='สาขา')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='doctor_profile', to=settings.AUTH_USER_MODEL, verbose_name='บัญชีผู้ใช้')),
            ],
            options={
                'verbose_name': 'แพทย์',
                'verbose_name_plural': 'แพทย์',
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขล่าสุดเมื่อ')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'จันทร์'), (1, 'อังคาร'), (2, 'พุธ'), (3, 'พฤหัสบดี'), (4, 'ศุกร์'), (5, 'เสาร์'), (6, 'อาทิตย์')], verbose_name='วันในสัปดาห์')),
                ('start_time', models.TimeField(verbose_name='เวลาเริ่มออกตรวจ')),
                ('end_time', models.TimeField(verbose_name='เวลาเลิกออกตรวจ')),
                ('is_active', models.BooleanField(default=True, verbose_name='ใช้งานอยู่')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doctor_schedules', to='clinics.clinic', verbose_name='สาขา')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='doctors.doctor', verbose_name='แพทย์')),
            ],
            options={
                'verbose_name': 'ตารางออกตรวจ',
                'verbose_name_plural': 'ตารางออกตรวจ',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='TimeBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขล่าสุดเมื่อ')),
                ('start_datetime', models.DateTimeField(db_index=True, verbose_name='เริ่มบล็อก')),
                ('end_datetime', models.DateTimeField(verbose_name='สิ้นสุดบล็อก')),
                ('reason', models.CharField(choices=[('lunch', 'พักเที่ยง'), ('meeting', 'ประชุม'), ('urgent_case', 'เคสด่วน'), ('leave', 'ลา'), ('other', 'อื่น ๆ')], default='other', max_length=20, verbose_name='เหตุผล')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='บันทึกเพิ่มเติม')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='ซ้ำตามรอบ')),
                ('recurrence', models.CharField(choices=[('none', 'ไม่ซ้ำ'), ('daily', 'ทุกวัน'), ('weekly', 'ทุกสัปดาห์')], default='none', max_length=10, verbose_name='รูปแบบการซ้ำ')),
                ('recurrence_end_date', models.DateField(blank=True, help_text='เว้นว่างหมายถึงซ้ำไปเรื่อย ๆ', null=True, verbose_name='ซ้ำถึงวันที่')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='time_blocks', to='clinics.clinic', verbose_name='สาขา')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_blocks', to='doctors.doctor', verbose_name='แพทย์')),
            ],
            options={
                'verbose_name': 'ช่วงเวลาที่ถูกบล็อก',
                'verbose_name_plural': 'ช่วงเวลาที่ถูกบล็อก',
                'ordering': ['start_datetime'],
            },
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['clinic', 'is_active'], name='doctors_doc_clinic__afa889_idx'),
        ),
        migrations.AddIndex(
            model_name='doctorschedule',
            index=models.Index(fields=['doctor', 'day_of_week', 'is_active'], name='doctors_doc_doctor__0d3163_idx'),
        ),
        migrations.AddConstraint(
            model_name='doctorschedule',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='doctor_schedule_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='doctorschedule',
            constraint=models.UniqueConstraint(fields=('doctor', 'day_of_week', 'start_time'), name='doctor_schedule_unique_start_per_day'),
        ),
        migrations.AddIndex(
            model_name='timeblock',
            index=models.Index(fields=['doctor', 'start_datetime'], name='doctors_tim_doctor__e70237_idx'),
        ),
        migrations.AddConstraint(
            model_name='timeblock',
            constraint=models.CheckConstraint(condition=models.Q(('end_datetime__gt', models.F('start_datetime'))), name='time_block_end_after_start'),
        ),
    ]
