# Generated by Django 5.2.17 on 2026-08-12 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขล่าสุดเมื่อ')),
                ('scheduled_start', models.DateTimeField(db_index=True, verbose_name='เวลานัดเริ่ม')),
                ('scheduled_end', models.DateTimeField(verbose_name='เวลานัดสิ้นสุด')),
                ('status', models.CharField(choices=[('booked', 'จองแล้ว'), ('confirmed', 'ยืนยันแล้ว'), ('checked_in', 'รอพบแพทย์'), ('in_progress', 'กำลังรักษา'), ('completed', 'เสร็จสิ้น'), ('cancelled', 'ยกเลิก'), ('no_show', 'ไม่มาตามนัด')], db_index=True, default='booked', max_length=15, verbose_name='สถานะ')),
                ('source', models.CharField(choices=[('staff_created', 'เจ้าหน้าที่จองให้'), ('walk_in', 'เดินเข้ามา (walk-in)')], default='staff_created', max_length=15, verbose_name='ที่มาของคิว')),
                ('note', models.CharField(blank=True, help_text='เช่น "แพ้ยาชา", "ขอหมอคนเดิม"', max_length=255, verbose_name='โน้ตสั้น')),
                ('checked_in_at', models.DateTimeField(blank=True, null=True, verbose_name='เวลาเช็คอิน')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='เวลาเริ่มรักษา')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='เวลาเสร็จสิ้น')),
                ('cancelled_reason', models.CharField(blank=True, max_length=255, verbose_name='เหตุผลที่ยกเลิก')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='clinics.clinic', verbose_name='สาขา')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='สร้างโดย')),
                ('doctor', models.ForeignKey(blank=True, help_text='เว้นว่างได้เฉพาะบริการที่ไม่ต้องมีแพทย์', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='doctors.doctor', verbose_name='แพทย์')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='patients.patient', verbose_name='คนไข้')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='services.servicetype', verbose_name='บริการ')),
            ],
            options={
                'verbose_name': 'การนัดหมาย',
                'verbose_name_plural': 'การนัดหมาย',
                'ordering': ['scheduled_start'],
                'indexes': [models.Index(fields=['clinic', 'scheduled_start'], name='scheduling__clinic__465355_idx'), models.Index(fields=['doctor', 'scheduled_start'], name='scheduling__doctor__7f4bc3_idx'), models.Index(fields=['status', 'scheduled_start'], name='scheduling__status_30cd1b_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('scheduled_end__gt', models.F('scheduled_start'))), name='appointment_end_after_start')],
            },
        ),
    ]
